### PR TITLE
feat: bolide - add polygon vault

### PR DESCRIPTION
**Pull request by Scriptoz**
- Bolide: a new polygon vault has been added
- Refactoring: move to a new API

### CODE REVIEW

**Review by witem — COMMENTED** [review]
Please fix eslint errors where it possible, like this: 
> `Unexpected any. Specify a different type`

**Comment by Scriptoz** [comment]
@witem 

> Please fix eslint errors where it possible, like this:
> 
> > `Unexpected any. Specify a different type`

@witem fixed

**Review by witem — APPROVED** [review]
LGTM. 
Do you have some example wallets to check that all data(for new and refactored features) is correct?

**Comment by Scriptoz** [comment]
> LGTM. Do you have some example wallets to check that all data(for new and refactored features) is correct?

Yes, I've already checked the data locally using test UI (http://localhost:8070) and all looks ok. Btw the link is always available and it provides data for all our vaults: https://bolide.fi/api/v1/vaults/list.

**Comment by witem** [comment]
> > LGTM. Do you have some example wallets to check that all data(for new and refactored features) is correct?
> 
> Yes, I've already checked the data locally using test UI (http://localhost:8070) and all looks ok. Btw the link is always available and it provides data for all our vaults: https://bolide.fi/api/v1/vaults/list.

@Scriptoz please provide a few examples for me and also you can test your changes on https://development.de.fi/

**Comment by Scriptoz** [comment]
> > > LGTM. Do you have some example wallets to check that all data(for new and refactored features) is correct?
> > 
> > 
> > Yes, I've already checked the data locally using test UI (http://localhost:8070) and all looks ok. Btw the link is always available and it provides data for all our vaults: https://bolide.fi/api/v1/vaults/list.
> 
> @Scriptoz please provide a few examples for me and also you can test your changes on https://development.de.fi/

@witem Here are some screenshots from local tests - all data seems to be correct. Sorry, I'm not familiar with https://development.de.fi/, so I don't know how to check the data on it.
image
image

**Comment by Scriptoz** [comment]
@witem Should I additionally do something in order to merge this PR?

**Comment by Scriptoz** [comment]
> @Scriptoz Yes, I need an example wallet addresses to check that all works as expected

@witem You can check data using this address, for example: `0x0228028a0c92cfd9743e561a96b16edbb4606054`

**Comment by witem** [comment]
@Scriptoz 
thanks. Do you expect only these farming positions to be displayed for the provided address?
image

Because I see some other positions for this wallet on bsc and polygon

https://development.de.fi/account/0x0228028a0c92cfd9743e561a96b16edbb4606054/dashboard/portfolio-overview

**Pull request merged**
